Revert: Address ROOT-9114 (Issues with dictionary's enum forward decl)
reverting https://github.com/root-project/root/commit/59c69dc2ce449eff8cabcf73405b04b07aaf9eb3 which caused build errors in 10_0_ROOT6 IBs.
```
>> Checking EDM Class Transients in libDataFormatsBTauReco.so
FWCore/Utilities/scripts/edmCheckClassTransients -l tmp/slc6_amd64_gcc630/src/DataFormats/BTauReco/src/DataFormatsBTauReco/libDataFormatsBTauReco.so -f lib/slc6_amd64_gcc630/DataFormatsBTauReco_xr.rootmap
In file included from DataFormatsBTauReco_xr dictionary payload:78:
In file included from DataFormats/BTauReco/interface/SecondaryVertexTagInfo.h:5:
In file included from DataFormats/BTauReco/interface/TemplatedSecondaryVertexTagInfo.h:15:
In file included from DataFormats/BTauReco/interface/TrackIPTagInfo.h:7:
  DataFormats/BTauReco/interface/IPTagInfo.h:179:24: error: no member named 'trackMomentum' in namespace 'reco::btau'
      vars.insert(btau::trackMomentum, trackMag, true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:180:24: error: no member named 'trackEta' in namespace 'reco::btau'
      vars.insert(btau::trackEta, trackMom.Eta(), true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:181:24: error: no member named 'trackEtaRel' in namespace 'reco::btau'
      vars.insert(btau::trackEtaRel, reco::btau::etaRel(jetDir, trackMom), true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:182:24: error: no member named 'trackPtRel' in namespace 'reco::btau'
      vars.insert(btau::trackPtRel, VectorUtil::Perp(trackMom, jetDir), true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:183:24: error: no member named 'trackPPar' in namespace 'reco::btau'
      vars.insert(btau::trackPPar, jetDir.Dot(trackMom), true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:184:24: error: no member named 'trackDeltaR' in namespace 'reco::btau'
      vars.insert(btau::trackDeltaR, VectorUtil::DeltaR(trackMom, jetDir), true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:185:24: error: no member named 'trackPtRatio' in namespace 'reco::btau'
      vars.insert(btau::trackPtRatio, VectorUtil::Perp(trackMom, jetDir) / trackMag, true);
                 ~~~~~~^
  DataFormats/BTauReco/interface/IPTagInfo.h:186:24: error: no member named 'trackPParRatio' in namespace 'reco::btau'
      vars.insert(btau::trackPParRatio, jetDir.Dot(trackMom) / trackMag, true);
```